AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Local testing template for Australian Ad Observatory API

Globals:
  Function:
    Timeout: 60
    MemorySize: 2048

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: local
      Cors:
        # '*' is NOT allowed with AllowCredentials: true.
        # List the specific origins your frontend runs on locally.
        AllowOrigin: "'http://localhost:5173'" # Add other local ports if needed (e.g., 3000) - single quotes required!
        AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        AllowCredentials: true # MUST be true if frontend sends Auth header or cookies (ours does)
        MaxAge: "'600'" # 10 minutes
  AaoApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: . # Points to the current directory (where lambda_function.py is)
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures: # Swap this to arm64 if you want to run on ARM locally but since the lambda is x86_64, we should keep it as that here
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi # Link to the API resource
            Path: /{proxy+} # Catch all paths
            Method: ANY