from enum import Enum

class Role(Enum):
    GUEST = "guest"     # Temporary, unauthenticated user. Generated by the system to expose certain resources.
    ADMIN = "admin"     # Administrator. Can access all resources.
    USER = "user"       # Authenticated user.
    
    @staticmethod
    def parse(role: str):
        return Role[role.upper()]

def authorise(*roles: list[Role]):
    def allows(event, response, context):
        print("Attempting to authorise", roles, "for", event)
        if 'user' not in event:
            response.status(401).json({
                "success": False,
                "comment": "MUST_USE_AFTER_AUTHENTICATE",
            })
            return event, response, context
        user = event['user']
        user_role = Role.parse(user['role'])
        if user_role not in roles:
            response.status(403).json({
                "success": False,
                "comment": f"Must be one of the following roles: {', '.join([role.value for role in roles])}, current role: {user_role}."
            })
            return event, response, context
        return event, response, context
    # Inject the documentation into the middleware function.
    allows.__doc__ = f"""
    --- summary
    {', '.join([role.value for role in roles])}
    --- description
    This endpoint requires the authenticated user to have one of the following roles: **{', '.join([role.value for role in roles])}**.
    """
    return allows