name: Feature request
description: Suggest an idea for this project (including improvements to existing features)
title: '[FEATURE] '
type: Feature
labels:
  - enhancement

body:
  - type: textarea
    attributes:
      label: Feature request
      description: A clear and concise description of the feature or improvement.
      placeholder: E.g., The app should...