"""update s3_url column to object_location for generalisation

Revision ID: 0ddf6d8edc96
Revises: 652f0e29c331
Create Date: 2026-01-15 10:06:39.863359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ddf6d8edc96'
down_revision: Union[str, Sequence[str], None] = '652f0e29c331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exports', sa.Column('object_location', sa.Text(), nullable=True))
    op.drop_column('exports', 's3_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exports', sa.Column('s3_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('exports', 'object_location')
    # ### end Alembic commands ###
