"""Add email column to users table

Revision ID: 54401bb69c05
Revises: 968306242c14
Create Date: 2025-07-23 09:58:02.953133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54401bb69c05'
down_revision: Union[str, Sequence[str], None] = '968306242c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('primary_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'primary_email')
    # ### end Alembic commands ###
