"""add export-related entities

Revision ID: 652f0e29c331
Revises: a09cf03e4bd5
Create Date: 2026-01-13 09:16:41.032289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652f0e29c331'
down_revision: Union[str, Sequence[str], None] = 'a09cf03e4bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exportable_fields',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('include_images', sa.Boolean(), nullable=False),
    sa.Column('query_string', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='exportstatus'), nullable=False),
    sa.Column('s3_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_fields',
    sa.Column('export_id', sa.String(), nullable=False),
    sa.Column('field_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['export_id'], ['exports.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['exportable_fields.id'], ),
    sa.PrimaryKeyConstraint('export_id', 'field_id')
    )
    op.create_table('shared_exports',
    sa.Column('export_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['export_id'], ['exports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('export_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_exports')
    op.drop_table('export_fields')
    op.drop_table('exports')
    op.drop_table('exportable_fields')
    # ### end Alembic commands ###
