"""add commercial content enrichment caching

Revision ID: 9f78b27ced9c
Revises: 134b005f627a
Create Date: 2026-02-09 12:49:23.714267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f78b27ced9c'
down_revision: Union[str, Sequence[str], None] = '134b005f627a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement_snapshots',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('ccl_enrichment_id', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ccl_enrichment_id', 'source_id', name='uq_snapshot_enrichment_source')
    )
    op.create_index(op.f('ix_advertisement_snapshots_ccl_enrichment_id'), 'advertisement_snapshots', ['ccl_enrichment_id'], unique=False)
    op.create_table('advertising_entities',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('ccl_enrichment_id', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ccl_enrichment_id', 'source_id', 'type', name='uq_entity_enrichment_source_type')
    )
    op.create_index(op.f('ix_advertising_entities_ccl_enrichment_id'), 'advertising_entities', ['ccl_enrichment_id'], unique=False)
    op.create_table('commercial_content_enrichments',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('observation_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('ad_type', sa.String(length=100), nullable=True),
    sa.Column('vendor', sa.Text(), nullable=False),
    sa.Column('scrape_started_at', sa.BigInteger(), nullable=True),
    sa.Column('scrape_completed_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_content_enrichments_observation_id'), 'commercial_content_enrichments', ['observation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commercial_content_enrichments_observation_id'), table_name='commercial_content_enrichments')
    op.drop_table('commercial_content_enrichments')
    op.drop_index(op.f('ix_advertising_entities_ccl_enrichment_id'), table_name='advertising_entities')
    op.drop_table('advertising_entities')
    op.drop_index(op.f('ix_advertisement_snapshots_ccl_enrichment_id'), table_name='advertisement_snapshots')
    op.drop_table('advertisement_snapshots')
    # ### end Alembic commands ###
